[build]
  base = "react_dashboard"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_BASE = "https://billboard-sentinel-backend.railway.app/api"

[context.deploy-preview.environment]
  REACT_APP_API_BASE = "https://billboard-sentinel-backend.railway.app/api"
