
version: "3.8"
services:
  web:
    build: .
    ports: ["8000:8000"]
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./app.db
  # For production replace sqlite with postgres/postgis service here
